### ISSUE TITLE
추가적 구현 사항

### ISSUE THREAD

**Issue by Minyeeun** [sth49/Final-Project#1]
특정 날짜 두개정도 정해서 날짜 클릭시 페이지 넘어가게 연동하기 (클릭 이벤트 발생 시 링크)

**Comment by sth49** [comment]
추가적으로 캘린더 페이지와 스터디플래너 페이지를 연동시키는 방법을 찾아봐야 할 것 같습니다

**Comment by Minyeeun** [comment]
구현하였습니다!
