### ISSUE TITLE
calander->daily

### ISSUE THREAD

**Issue by sth49** [sth49/Final-Project#18]
Calander 페이지에서 daily planner 페이지로 넘어가는 것이 기존에는 버튼을 누르면 현재 날짜만 접근할 수 있도록 했었는데 이제는 날짜별로 버튼을 누르면 각 날짜에 맞는 daily planner 페이지로 넘어갈 수 있도록 바꾸었습니다.

**Comment by Minyeeun** [comment]
네 알겠습니다 확인했습니다
