### ISSUE TITLE
Desktop app 화면 겹침

### ISSUE THREAD

**Issue by sth49** [sth49/Final-Project#19]
Electron을 이용해 Desktop app으로 만들어 보았는데, 창 크기에 따라서 화면이 겹쳐보이는 현상이 나타납니다.
calendar.html과 각 날짜별 html파일에서 겹쳐보이지 않게 각 요소들의 크기를 조정해야 할 것 같습니다

**Comment by Minyeeun** [comment]
비율 조정했습니다:)
