### ISSUE TITLE
페이지 연동 관련 이슈

### ISSUE THREAD

**Issue by sth49** [sth49/Final-Project#3]
캘린더 페이지에서 스터디 플래너 페이지로 넘어가기 위해서 어떤식으로 구현하면 좋을까요?

**Comment by Minyeeun** [comment]
버튼을 만들어서 구현하면 될 것 같아요!

**Comment by Minyeeun** [comment]
https://wallel.com/onclick-%EB%A7%81%ED%81%AC-%EC%83%88%EC%B0%BD%ED%8C%9D%EC%97%85%ED%98%84%EC%9E%AC%EC%B0%BD%ED%94%84%EB%A0%88%EC%9E%84/ 
이거 참고하시면 좋을 것 같아요

**Comment by sth49** [comment]
감사합니다~~

**Comment by sth49** [comment]
링크 참고해서 캘린더 페이지와 스터디 플래너 페이지를 버튼으로 연동하였습니다

**Comment by Minyeeun** [comment]
네넹 확인했습니다! 감사합니다
