### ISSUE TITLE
테이블과 할일 목록 중

### ISSUE THREAD

**Issue by Minyeeun** [sth49/Final-Project#5]
테이블과 할일 목록 중에서 테이블 식으로 구현하는 것보다 할일을 빠르게 추가하게 만드는 것이 좋아보이는 데 어떻게 생각해요??

**Comment by sth49** [comment]
저도 후자가 더 좋을거같아요!!

**Comment by Minyeeun** [comment]
네 알겠습니다! 의견 감사합니다:)
