### ISSUE TITLE
daily plan 디자인 관련질문

### ISSUE THREAD

**Issue by Minyeeun** [sth49/Final-Project#9]
컬러칩 팔레트에 색을 7개만해서 넣어놓으니까 어색한데 색을 늘려서 (한 12개 정도?) 두줄로 만들면 어떨까요??

**Comment by sth49** [comment]
좋을 것 같아요! 크기랑 위치 조정은 시간나면 제가 할게요!

**Comment by Minyeeun** [comment]
넵 팔레트 색상 뽑아서 올리겠습니다!
